name: Build Android

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-30"
          sdkmanager "build-tools;30.0.3"

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Setup Haxelib
        run: haxelib setup ~/haxelib

      # CACHE HAXELIB
      - name: Cache Haxelib
        uses: actions/cache@v4
        with:
          path: |
            ~/haxelib
            ~/.cache/haxelib
          key: haxelib-${{ runner.os }}-4.2.5

      # CACHE HXCPP
      - name: Cache hxcpp
        uses: actions/cache@v4
        with:
          path: |
            ~/.hxcpp
          key: hxcpp-${{ runner.os }}

      - name: Install Libraries
        run: |
          haxelib install hxcpp --quiet
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install hxCodec --quiet
          haxelib install hscript --quiet

      - name: Install Git Libraries
        run: |
          git clone https://github.com/Aidan63/linc_discord-rpc discord_rpc
          haxelib dev discord_rpc discord_rpc

          git clone https://github.com/Dot-Stuff/flxanimate flxanimate
          haxelib dev flxanimate flxanimate

          git clone https://github.com/superpowers04/linc_luajit linc_luajit
          haxelib dev linc_luajit linc_luajit

          git clone https://github.com/MatheusSilver/extension-webview extension-webview
          haxelib dev extension-webview extension-webview

          git clone https://github.com/MAJigsaw77/extension-androidtools extension-androidtools
          haxelib dev extension-androidtools extension-androidtools

      - name: Rebuild LuaJIT
        run: |
          haxelib run lime rebuild linc_luajit android

      - name: Configure Lime
        run: |
          haxelib run lime setup -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk